# Generated by Django 4.2.16 on 2025-11-15 08:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('picker', 'Picker'), ('packer', 'Packer')], default='picker', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_base_url', models.URLField(max_length=500)),
                ('sync_interval_minutes', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='never', max_length=20)),
                ('last_sync_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configuration',
                'db_table': 'api_configuration',
            },
        ),
        migrations.CreateModel(
            name='EmailSMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('notification_recipients', models.JSONField(default=list)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255)),
                ('twilio_from_number', models.CharField(blank=True, max_length=20)),
                ('sms_recipients', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email/SMS Settings',
                'verbose_name_plural': 'Email/SMS Settings',
                'db_table': 'email_sms_settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('number', models.CharField(db_index=True, max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('picking', 'Picking in Progress'), ('ready_to_pack', 'Ready to Pack'), ('packed', 'Packed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('ready_to_pack', models.BooleanField(db_index=True, default=False)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('item_type', models.CharField(default='product', max_length=50)),
                ('store_quantity_available', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['category', 'sku'],
                'indexes': [models.Index(fields=['sku'], name='products_sku_fe2039_idx'), models.Index(fields=['category'], name='products_categor_fce6e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('qty_ordered', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qty_picked', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty_short', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.product')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['order__created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('orders_fetched', models.IntegerField(default=0)),
                ('orders_created', models.IntegerField(default=0)),
                ('orders_updated', models.IntegerField(default=0)),
                ('products_created', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at'], name='sync_logs_started_2c7a3f_idx'), models.Index(fields=['status'], name='sync_logs_status_e8f5ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('product_title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('qty_short', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order_numbers', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_exceptions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sku'], name='stock_excep_sku_fd4758_idx'), models.Index(fields=['timestamp'], name='stock_excep_timesta_96a276_idx'), models.Index(fields=['resolved'], name='stock_excep_resolve_852f77_idx')],
            },
        ),
        migrations.CreateModel(
            name='PickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_events', to='api.orderitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pick_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='pick_events_timesta_189219_idx'), models.Index(fields=['order_item'], name='pick_events_order_i_1fcbb3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku'], name='order_items_sku_1b9f90_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'sku'], name='order_items_order_i_be4219_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['external_order_id'], name='orders_externa_1cd7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ready_to_pack'], name='orders_ready_t_e03ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
    ]
