# Generated by Django 4.2.16 on 2025-11-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default='staff', max_length=20),
        ),
    ]
