# Generated by Django 4.2.16 on 2025-11-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_update_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsmssettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
