# Generated by Django 4.2.16 on 2025-11-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_smtp_use_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexception',
            name='ordered_from_company',
            field=models.BooleanField(default=False),
        ),
    ]
