# Generated by Django 4.2.16 on 2025-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_ordered_from_company_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
