# Generated by Django 4.2.16 on 2025-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_vendor_name_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
