# Generated by Django 4.2.16 on 2025-11-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fix_vendor_name_null_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='detailed_errors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
