# Generated by Django 4.2.16 on 2025-11-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_detailed_errors_to_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
