# Generated by Django 4.2.16 on 2025-11-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_variation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexception',
            name='na_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
