# Generated by Django 4.2.16 on 2025-11-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_na_cancel_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
